# Constants
DEFAULT_UPDATED_THRESHOLD = 1500
DEFAULT_VTRUST_THRESHOLD = 0.01
DEFAULT_STOPPED_LOGS_THRESHOLD = 30
DEFAULT_LOG_ERRORS_RESTART_WAIT_TIME = 3

RESTARTER_PREFIX = "RESTARTER"

RED_X = "\u274C"
RED_QM = "\u2753"
RED_EP = "\u203C\uFE0F"
DISCORD_MONITOR_URL = (
    "https://discord.com/api/webhooks/1328849265765777468/"
    "yJg07DYWLJyiFZgZPaLGTmFEwiAu2JWW5osyjFVoqlMWT66JBbV9_FOcslvDdtibtcR0"
)

RESTARTER_GIT_PATHS = ["bin/restart_bad_validator", "restarter"]

# Debugging
DEBUG = False
