#!/usr/bin/env python3

# Reference docs for calculating alpha price
# https://docs.taostats.io/docs/alpha-emission
# https://docs.taostats.io/docs/subnet-pools

# Standard imports
import argparse
import asyncio
from dataclasses import dataclass, field
from rich.text import Text
from rich.console import Console

# Bittensor import
import bittensor


LEGIT_VALI_COLDKEYS = {
    "5FuzgvtfbZWdKSRxyYVPAPYNaNnf9cMnpT7phL3s2T3Kkrzo": "Rizzo",
    "5GW9X8GyXwA3VQbNhnzb6sJmfPvKBBJwx19hJrCseverjovV": "Rt21",
    "5EBuUXD6eXSSWVaT1NqaUQoAACUkAmEogzAfPQvDXTEQZ8Ff": "OTF",
    "5E9fVY1jexCNVMjd2rdBsAxeamFGEMfzHcyTn2fHgdHeYc5p": "Yuma",
    "5FHxxe8ZKYaNmGcSLdG5ekxXeZDhQnk9cbpHdsJW8RunGpSs": "Kraken",
    "5CWzmvA17MAMQ9mnAecLxFXS2N8846rz6T7m4QNHyVtJVq4j": "TAO.com",
}

WEIGHT_COPIER_COLDKEYS = {
    "5EJAqczgzCMvWcmXhKMZH4vMS5gPy8BjeuHjz5o5yN6RYzX2": "Tao5 (WC)",
    "5GsbTgfvgCH4xdqSkiPb7EaBBFLHjWH5vfEALhJaewSFpZX9": "Tao.bot (WC)",
    "5Ek8i6wDRakJfJPM9wpJLYDE9G9uaqHLdARoewtTiLtbt33f": "1T1B.AI (WC)",
    "5GP1VN5DcMNW5XL6cAFEzneN9fTfWMytNibZX8YMS7BgJBG6": "Kooltek68 (WC)",
    "5Eq8b9p6zJMjEXyH9sX4DRMYspnUyorEKq3Zmha1WN6AC4sf": "Crucible Labs (WC)",
    "5HiFDVNX4ivCJFt9RvgRCtQKmAPgAXGX8BRgX3XKqfY9fFve": "TAO.app (WC)",
    "5DkwfxC9mZTTCsRUt6nrnwQEWVrhsmY13SBRparj6cpAVxVY": "Datura",
    "5F4XcaiEBkE3ARx2kG29KJ8e94nFfUZQYC4c7zfticastxiD": "Weight Copier",
    "5DyMLUKuc6T3QFAXKd3w6dTcxmcH1WBZ1gDrRwJAnPf7N28w": "Weight Copier",
    "5EnXts8HKLv1o3qhFBGPaoZt1CjMd2g4RtKDpnp3A44xFCGK": "Weight Copier",  # 5FLoWC...SeRv8m
    "5CqsgERpW6dJn4AtTkfckcUd7Ab6JNVa2Hb2MhyjApYVXMUV": "MUV",
    "5DywxdtESjskgPZrDXL86qV44SpPgJuqs9X6noyJJwX9PaSD": "General Tensor",
}


@dataclass
class StakeData:
    @dataclass
    class AlphaTuple:
        stake: float
        price: float

    stake_in_alpha: dict = field(default_factory=dict)
    stake_in_tao: float = 0.0


def parse_args():
    parser = argparse.ArgumentParser()

    # parser.add_argument(
    #     "type",
    #     choices=["stake", "reg", "vt", "vtea"],
    #     help="Only display the top validators up to this number. For example, "
    #             "--top 50 shows only the top 50 validators.")

    parser.add_argument(
        "--top",
        type=int,
        help="Only display the top validators up to this number. For example, "
             "--top 50 shows only the top 50 validators.")

    parser.add_argument(
        "-l", "--local-subtensor",
        help="Use the specified local subtensor (i.e. la, cali, titan, etc.). "
             "When not specified, use the 'finney' network subtensor."
    )

    return parser.parse_args()


def get_network(name):
    if not name:
        return "finney"
    return name if ":" in name else f"ws://subtensor-{name}.rizzo.network:9944"


async def get_metagraphs():
    network = get_network(args.local_subtensor)
    print(f"Connecting to {network}")

    async with bittensor.Subtensor(network=network) as subtensor:
        # Get a snapshot of the subtensor at the current block so everything is in sync
        # in case data gathering take multiple blocks.
        block = await subtensor.block()
        subtensor_snapshot = await subtensor.at(block)

        # Get all subnets
        subnets = await subtensor_snapshot.subnets.all()
        netuids = [sn.netuid for sn in subnets][1:]

        # Get the metagraph for each netuid
        metagraphs = await asyncio.gather(
            *[subtensor_snapshot.subnets.metagraph(netuid) for netuid in netuids]
        )

    return metagraphs


def update_validators_stake(validators_stake, metagraph):
    alpha_price = metagraph.price
    for validator in metagraph.validators:
        stake_in_alpha = validator.total_stake.amount
        stake_in_tao = stake_in_alpha * alpha_price

        stake_data = validators_stake.setdefault(validator.coldkey, StakeData())
        stake_data.stake_in_alpha[metagraph.netuid] = \
            StakeData.AlphaTuple(stake=stake_in_alpha, price=alpha_price)
        stake_data.stake_in_tao += stake_in_tao


def print_stake_rankings(validators_stake, num_total):
    def get_tao_stake(coldkey):
        return validators_stake[coldkey].stake_in_tao

    print("")
    text = Text()

    for rank, coldkey in enumerate(reversed(sorted(validators_stake, key=get_tao_stake)), 1):
        if rank > num_total:
            break

        text.append(f"{rank:<2} - ")
        if coldkey in LEGIT_VALI_COLDKEYS:
            name = LEGIT_VALI_COLDKEYS[coldkey]
            color = 10 if name == "Rizzo" else 12
            style = f"color({color})"
        elif coldkey in WEIGHT_COPIER_COLDKEYS:
            name = WEIGHT_COPIER_COLDKEYS[coldkey]
            color = 9
            style = f"color({color})"
        else:
            name = coldkey[:6] + "..." + coldkey[-6:]
            style = None
        text.append(f"{name:<15}", style=style)

        stake_data = validators_stake[coldkey]
        text.append("  --  ")
        text.append(f"{stake_data.stake_in_tao:.3f}\n", style=style)

    Console().print(text)


async def main(args):
    metagraphs = await get_metagraphs()

    validators_stake = {}
    for metagraph in metagraphs:
        update_validators_stake(validators_stake, metagraph)

    num_total = args.top or len(validators_stake)
    print_stake_rankings(validators_stake, num_total)


if __name__ == "__main__":
    try:
        args = parse_args()
        asyncio.run(main(args))
    except KeyboardInterrupt as exc:
        import traceback
        exc_list = traceback.format_exception_only(exc)
        exc_text = "\n" + "".join(exc_list).strip("\n")
        print(exc_text)
