#!/usr/bin/env python3

# Reference docs for calculating alpha price
# https://docs.taostats.io/docs/alpha-emission
# https://docs.taostats.io/docs/subnet-pools

# Standard imports
import argparse
import asyncio
from dataclasses import dataclass, fields, asdict
import json
import math
import multiprocessing
import os
from rich.text import Text
from rich.console import Console
import sys
import time

# Bittensor import
import bittensor

# Add local helper_scripts dir to path for importing helper_scripts_common.py
sys.path = [os.path.dirname(__file__)] + sys.path

# Local imports
from helper_scripts_common import (
    LEGIT_VALI_COLDKEYS,
    WEIGHT_COPIER_COLDKEYS,
    logger,
    get_formatted_time,
    get_lite_subtensor_network,
    SubtensorConnectionError,
)


JSON_FILE_NAME = "validator_ranking.json"


def parse_args():
    parser = argparse.ArgumentParser()

    parser.add_argument(
        "-j", "--json-folder",
        help="If this is specified then the validator rankings are written to a json file "
                "in the specified folder. If not specified then the validator rankings are "
                "printed to stdout."
    )

    parser.add_argument(
        "-i", "--interval",
        type=float,
        default=0,
        help="The number of minutes between validator data gathering. If 0 or not "
             "specified then the data is gathered only once."
    )

    parser.add_argument(
        "--min-subnets",
        type=int,
        default=1,
        help="Only display the validators validating on at least this number of "
                "subnets. The default value is 1, do each displayed validator must "
                "be validating on at least 1 subnet."
    )

    parser.add_argument(
        "--sort",
        type=int,
        choices=list(range(1, len(fields(RankValidators.ValidatorData)) + 1)),
        default=1,
        help="The criteria by which to rank the validator. The choices are the column "
             "numbers of the printout where the S column is the first column. The default "
             "is the first column."
    )

    parser.add_argument(
        "--top",
        type=int,
        help="Only display the top validators up to this number. For example, "
             "--top 50 shows only the top 50 validators."
    )

    parser.add_argument(
        "-l", "--local-subtensor",
        nargs="?",
        default=False,
        help="Use the specified local subtensor (i.e. la, cali, titan, etc.). "
             "When not specified, use the 'finney' network subtensor."
    )

    return parser.parse_args()


class RankValidators:

    @dataclass
    class ValidatorData:
        # Validator name
        validator_name: str

        # The type of validator.
        # This isn't an enum because it's stored and read by the ValidatorStatus page
        # 0 - Unknown
        # 1 - Rizzo validator
        # 2 - Legitimate validator
        # 3 - Weight Copier
        validator_type: int

        # Total number of subnets on which the validator is setting weights.
        total_subnets: int = 0

        # Total number of subnets with emission on which the validator is setting weights.
        total_emitting_subnets: int = 0

        # Average vTrust weighted by subnet emission.
        weighted_vtrust: float = 0.0

        # Total validator dividends per 100,000 stake weighted by subnet emission.
        normalized_dividends: float = 0.0

        # Total stake on subnets being validated on.
        total_stake: float = 0.0

        # Total stake on subnets being validated on weighted by subnet emission.
        total_emission_stake: float = 0.0

        # Total validator emission per 100,000 stake weighted by subnet emission.
        # I think this one isn't very accurate because it looks like the emission values
        # also include emissions to the subnet owner.
        # normalized_emission: float = 0.0

    def __init__(self, args):
        self._min_subnets = args.min_subnets
        self._json_folder = args.json_folder
        self._sort = args.sort + 2
        self._top = args.top
        self._network = args.network
        self._run()

    def _run(self):
        asyncio.run(self._get_data_from_subtensor())
        self._get_validator_stats()
        self._filter_validators()
        if self._json_folder:
            self._write_json_file()
        else:
            self._print_validator_ranking()

    async def _get_data_from_subtensor(self):
        logger.info(f"Connecting to {self._network}")

        try:
            async with bittensor.Subtensor(network=self._network) as subtensor:
                # Get a snapshot of the subtensor at the current block so everything is in sync
                # in case data gathering takes multiple blocks.
                block = await subtensor.block()
                snapshot = await subtensor.at(block)

                # Get all subnets.
                subnets = await snapshot.subnets.all()
                netuids = [sn.netuid for sn in subnets][1:]
                self._total_subnets = len(netuids)

                # Get the metagraph for each netuid.
                self._metagraphs = await asyncio.gather(
                    *[
                        snapshot.subnets.metagraph(netuid, commitments=False)
                        for netuid in netuids
                    ]
                )

                # Get the mech splits for each subnet as a list of fractions.
                self._mech_splits = await asyncio.gather(
                    *[self._get_mech_splits(snapshot, netuid) for netuid in netuids]
                )

                # Get the emission for each subnet as a fraction of the total emission.
                self._subnet_emissions = await self._get_subnet_emissions(snapshot, netuids)

                # Get the validators' vTrusts for each subnet.
                self._vtrusts = await asyncio.gather(
                    *[self._get_subnet_vtrusts(snapshot, netuid) for netuid in netuids]
                )

                # Get the validators' updated blocks for each mech on each subnet.
                self._updateds = await asyncio.gather(
                    *[self._get_subnet_updateds(snapshot, netuid) for netuid in netuids]
                )
        except Exception as err:
            logger.error("")
            logger.error(f"Subtensor connection failed on '{self._network}'")
            logger.error(f"{type(err).__name__}: {err}")
            logger.error("")
            raise SubtensorConnectionError

    async def _get_mech_splits(self, snapshot, netuid):
        # mechanism_emission_split will return None for subnets that have one mech
        # so replace None with a list with a single emission fraction of 1.0
        mech_split = await snapshot.subnets.mechanism_emission_split(netuid)
        return (
            [(m / bittensor.settings.U16_MAX) for m in mech_split]
            if mech_split else [1.0]
        )

    async def _get_subnet_emissions(self, snapshot, netuids):
        tao_emission = await asyncio.gather(
            *[
                snapshot.query(
                    bittensor.storage.SubtensorModule.SubnetTaoInEmission,
                    params=[netuid]
                )
            for netuid in netuids
            ]
        )
        excess_tao = await asyncio.gather(
            *[
                snapshot.query(
                    bittensor.storage.SubtensorModule.SubnetExcessTao,
                    params=[netuid]
                )
            for netuid in netuids
            ]
        )
        raw_emission = [tao_emission[ni] + excess_tao[ni] for ni in range(self._total_subnets)]
        total_emission = sum(raw_emission)
        return [e / total_emission for e in raw_emission]

    async def _get_subnet_vtrusts(self, snapshot, netuid):
        raw_vtrusts = await snapshot.query(
            bittensor.storage.SubtensorModule.ValidatorTrust,
            params=[netuid]
        )
        return [vt / bittensor.settings.U16_MAX for vt in raw_vtrusts]

    async def _get_subnet_updateds(self, snapshot, netuid):
        updateds = []
        mechs = await snapshot.subnets.mechanism_count(netuid)
        for mechid in range(mechs):
            last_updates_index = mechid * bittensor.settings.GLOBAL_MAX_SUBNET_COUNT + netuid
            last_updates = await snapshot.query(
                bittensor.storage.SubtensorModule.LastUpdate,
                params=[last_updates_index]
            )
            updateds.append([snapshot.block - lu for lu in last_updates])
        return updateds

    def _get_validator_stats(self):
        self._validator_data = {}

        # Loop through all metagraphs and gather up all validator data.
        for ni in range(self._total_subnets):
            metagraph = self._metagraphs[ni]
            mech_split = self._mech_splits[ni]
            subnet_emission = self._subnet_emissions[ni]
            vtrust = self._vtrusts[ni]
            updated = self._updateds[ni]
            alpha_price = metagraph.price

            for validator in metagraph.validators:
                coldkey = validator.coldkey
                if coldkey not in self._validator_data:
                    vali_name, vali_type = self._get_vali_name_and_type(validator)
                    self._validator_data[coldkey] = self.ValidatorData(
                        validator_name=vali_name,
                        validator_type=vali_type,
                    )
                validator_data = self._validator_data[coldkey]

                # Some owner neurons have a validator permit but no stake.
                if not validator.total_stake.alpha:
                    continue

                # Filter validators by last updated. If the validator's updated value
                # for any non-zero emission mechanism < 5000 then it can be considered
                # as legitimately validating.
                for mechid, mech_emission in enumerate(mech_split):
                    if mech_emission and updated[mechid][validator.uid] < 5000:
                        break
                else:
                    continue

                # Total number of subnets on which the validator is setting weights.
                validator_data.total_subnets += 1

                # Total number of subnets with emission on which the validator is setting weights.
                if subnet_emission:
                    validator_data.total_emitting_subnets += 1

                # Total stake on subnets being validated on.
                validator_data.total_stake += validator.total_stake.alpha * alpha_price

                # Total stake on subnets being validated on weighted by subnet emission.
                validator_data.total_emission_stake += (
                    validator.total_stake.alpha * alpha_price * subnet_emission
                )

                # Average vTrust weighted by subnet emission.
                validator_data.weighted_vtrust += vtrust[validator.uid] * subnet_emission

                # Total validator dividends per 100,000 stake weighted by subnet emission.
                validator_data.normalized_dividends += (
                    100000 * validator.dividends / validator.total_stake.alpha * subnet_emission
                )

                # Total validator emission per 100,000 stake weighted by subnet emission.
                # I think this one isn't very accurate because it looks like the emission values
                # also include emissions to the subnet owner.
                # validator_data.normalized_emission += (
                #     100000 * validator.emission.alpha / validator.total_stake.alpha * subnet_emission
                # )

    def _filter_validators(self):
        for coldkey in list(self._validator_data):
            validator_data = self._validator_data[coldkey]
            if validator_data.total_subnets < self._min_subnets:
                del self._validator_data[coldkey]
            validator_data.total_stake = int(validator_data.total_stake)
            validator_data.total_emission_stake = int(validator_data.total_emission_stake)

    def _write_json_file(self):
        json_file = os.path.join(self._json_folder, JSON_FILE_NAME)

        # Get a serializable version of the data
        json_data = {k: asdict(v) for k, v in self._validator_data.items()}
        timestamp = int(time.time())
        json_contents = {
            "data": json_data,
            "timestamp": timestamp,
        }

        # First remove the existing json file
        if os.path.isfile(json_file):
            logger.info("Removing %s", json_file)
            os.unlink(json_file)

        # Then write the new data json file
        logger.info("Writing data to file: %s", json_file)
        with open(json_file, "w") as fd:
            json.dump(json_contents, fd, indent=4)

    def _print_validator_ranking(self):
        num_total = self._top or len(self._validator_data)
        rank_padding = int(math.log(num_total, 10)) + 1
        name_padding = self._get_vali_name_length()

        text = Text()
        text.append("\n\n")
        text.append("S      -- Total number of subnets on which the validator is setting weights.\n")
        text.append("SE     -- Total number of subnets with emission on which the validator is setting weights.\n")
        text.append("vTW    -- Average vTrust weighted by subnet emission.\n")
        text.append("DivW   -- Total validator dividends per 100,000 stake weighted by subnet emission.\n")
        text.append("Stake  -- Total stake on subnets being validated on.\n")
        text.append("StakeE -- Total stake on subnets being validated on weighted by subnet emission.\n")
        # text.append("Total validator emission per 100,000 stake weighted by subnet emission.\n")
        text.append("\n\n")

        text.append(" " * (rank_padding + 3))
        text.append("Name" + " " * (name_padding + 2))
        text.append("S     ")
        text.append("SE    ")
        text.append("vTW     ")
        text.append("DivW      ")
        text.append("Stake    ")
        text.append("StakeE")
        text.append("\n" + "-" * (rank_padding + name_padding + 54) + "\n")

        for rank, coldkey in enumerate(reversed(sorted(
            self._validator_data, key=self._get_sort_key
        )), 1):

            if rank > num_total:
                break

            validator_data = self._validator_data[coldkey]
            name = validator_data.validator_name
            color = {
                0: "default",
                1: "bright_green",
                2: "bright_blue",
                3: "bright_red",
            }.get(validator_data.validator_type)

            text.append(f"{rank:<{rank_padding}} - ")
            text.append(f"{name:<{name_padding}}", style=color)
            text.append("  --  ")
            text.append(
                f"{validator_data.total_subnets:<6}"
                f"{validator_data.total_emitting_subnets:<6}"
                f"{validator_data.weighted_vtrust:<8.3f}"
                f"{validator_data.normalized_dividends:<10.5f}"
                f"{validator_data.total_stake:<9}"
                f"{validator_data.total_emission_stake}"
                # f"{validator_data.normalized_emission:8.4f}"
                "\n",
                style=color
            )

        Console().print(text)

    def _get_vali_name_length(self):
        num_total = self._top or len(self._validator_data)
        max_length = 0
        for rank, coldkey in enumerate(reversed(sorted(
            self._validator_data, key=self._get_sort_key
        )), 1):
            if rank > num_total:
                break
            validator_data = self._validator_data[coldkey]
            length = len(validator_data.validator_name)
            if length > max_length:
                max_length = length
        return max_length

    @staticmethod
    def _get_vali_name_and_type(validator):
        coldkey = validator.coldkey
        identity = validator.identity
        vali_name = (identity or {}).get("name") or None
        # This is SO HACKY!!
        if vali_name:
            if "/" in vali_name:
                vali_name = vali_name.split("/")[0]
            vali_name = vali_name.strip()

        if coldkey in LEGIT_VALI_COLDKEYS:
            vali_name = vali_name or LEGIT_VALI_COLDKEYS[coldkey]
            vali_type = 1 if LEGIT_VALI_COLDKEYS[coldkey] == "Rizzo" else 2
        elif coldkey in WEIGHT_COPIER_COLDKEYS:
            vali_name = vali_name or WEIGHT_COPIER_COLDKEYS[coldkey]
            vali_type = 3
        else:
            vali_name = vali_name or coldkey[:6] + "..." + coldkey[-6:]
            vali_type = 0

        return vali_name, vali_type

    def _get_sort_key(self, coldkey):
        validator_data = self._validator_data[coldkey]
        sort_attr = fields(validator_data)[self._sort - 1].name
        return getattr(validator_data, sort_attr)


def main():
    args = parse_args()

    interval_seconds = round(args.interval * 60)

    while True:
        logger.info("Getting validator ranking.")
        start_time = time.time()

        args.network = get_lite_subtensor_network(args.local_subtensor)

        try:
            with multiprocessing.Pool(processes=1) as pool:
                pool.apply(RankValidators, [args])
        except SubtensorConnectionError:
            if args.local_subtensor is None:
                logger.info("Rotating subtensors and trying again.")
                time.sleep(1)
                continue

        total_seconds = round(time.time() - start_time)
        total_time_formatted = get_formatted_time(total_seconds)
        logger.info("Validator rank data gathering took %s.\n", total_time_formatted)

        # Only gather the data once.
        if not interval_seconds:
            break

        wait_seconds = interval_seconds - total_seconds
        if wait_seconds > 0:
            wait_time_formatted = get_formatted_time(wait_seconds)
            logger.info("Waiting %s.", wait_time_formatted)
            time.sleep(wait_seconds)
        else:
            logger.warning(
                "Processing took %i seconds which is longer than %i seconds. Not waiting.",
                total_seconds, interval_seconds
            )


if __name__ == "__main__":
    try:
        main()
    except KeyboardInterrupt as exc:
        import traceback
        exc_list = traceback.format_exception_only(exc)
        exc_text = "\n" + "".join(exc_list).strip("\n")
        print(exc_text)
