#!/usr/bin/env python3

# Standard imports
import argparse
import asyncio
import os
import sys

# Bittensor import
import bittensor

# Add local helper_scripts dir to path for importing helper_scripts_common.py
sys.path = [os.path.dirname(__file__)] + sys.path

# Local imports
from helper_scripts_common import get_lite_subtensor_network


def parse_args():
    parser = argparse.ArgumentParser()

    parser.add_argument(
        "-s",
        type=int,
        dest="netuids",
        nargs="+",
        help="The uids of the subnets to check. If not specified then all subnets are checked.")

    parser.add_argument(
        "-l", "--local-subtensor",
        nargs="?",
        default=False,
        help="Use the specified local subtensor (i.e. la, cali, titan, etc.). "
             "When not specified, use the 'finney' network subtensor."
    )

    return parser.parse_args()


async def main():
    args = parse_args()

    network = get_lite_subtensor_network(args.local_subtensor)
    print(f"Connecting to {network}")

    print("")
    print("Subnets with multiple mechanisms")
    print("=================================")

    async with bittensor.Subtensor(network=network) as subtensor:
        if args.netuids:
            netuids = args.netuids
        else:
            subnets = await subtensor.subnets.all()
            netuids = [sn.netuid for sn in subnets][1:]

        mechs_list = await asyncio.gather(
            *[
                subtensor.subnets.mechanism_count(netuid)
                for netuid in netuids
            ]
        )

        # TODO: Only use asyncio.gather to get the emission splits if the
        # number of subnets using multiple mechanisms gets large.
        # emission_list = await asyncio.gather(
        #     *[
        #         subtensor.subnets.mechanism_emission_split(netuid)
        #         for netuid in netuids
        #     ]
        # )

        for netuid, mechs in zip(netuids, mechs_list):
            if mechs > 1:
                emission = await subtensor.subnets.mechanism_emission_split(netuid)
                emission = [round((e / bittensor.settings.U16_MAX) * 100) for e in emission]
                emission = ", ".join([f"{e}%" for e in emission])
                netuid = f"{netuid}:"
                print(f"{netuid:<4} {mechs} ({emission})")

    print("")


if __name__ == "__main__":
    try:
        asyncio.run(main())
    except KeyboardInterrupt as exc:
        import traceback
        exc_list = traceback.format_exception_only(exc)
        exc_text = "\n" + "".join(exc_list).strip("\n")
        print(exc_text)
