#!/usr/bin/env python3

import argparse
from rich.text import Text
from rich.console import Console
import sys


LEGIT_VALI_COLDKEYS = {
    "5FuzgvtfbZWdKSRxyYVPAPYNaNnf9cMnpT7phL3s2T3Kkrzo": "Rizzo",
    "5DywxdtESjskgPZrDXL86qV44SpPgJuqs9X6noyJJwX9PaSD": "Rt21",
    "5EBuUXD6eXSSWVaT1NqaUQoAACUkAmEogzAfPQvDXTEQZ8Ff": "OTF",
    "5E9fVY1jexCNVMjd2rdBsAxeamFGEMfzHcyTn2fHgdHeYc5p": "Yuma",
    "5FHxxe8ZKYaNmGcSLdG5ekxXeZDhQnk9cbpHdsJW8RunGpSs": "Kraken",
    "5CWzmvA17MAMQ9mnAecLxFXS2N8846rz6T7m4QNHyVtJVq4j": "TAO.com",
    "5CqsgERpW6dJn4AtTkfckcUd7Ab6JNVa2Hb2MhyjApYVXMUV": "MUV",
}

WEIGHT_COPIER_COLDKEYS = {
    "5EJAqczgzCMvWcmXhKMZH4vMS5gPy8BjeuHjz5o5yN6RYzX2": "Tao5 (WC)",
    "5GsbTgfvgCH4xdqSkiPb7EaBBFLHjWH5vfEALhJaewSFpZX9": "Tao.bot (WC)",
    "5Ek8i6wDRakJfJPM9wpJLYDE9G9uaqHLdARoewtTiLtbt33f": "1T1B.AI (WC)",
    "5GP1VN5DcMNW5XL6cAFEzneN9fTfWMytNibZX8YMS7BgJBG6": "Kooltek68 (WC)",
    "5Eq8b9p6zJMjEXyH9sX4DRMYspnUyorEKq3Zmha1WN6AC4sf": "Crucible Labs (WC)",
    "5HiFDVNX4ivCJFt9RvgRCtQKmAPgAXGX8BRgX3XKqfY9fFve": "TAO.app (WC)",
    "5F4XcaiEBkE3ARx2kG29KJ8e94nFfUZQYC4c7zfticastxiD": "Weight Copier",
    "5DyMLUKuc6T3QFAXKd3w6dTcxmcH1WBZ1gDrRwJAnPf7N28w": "Weight Copier",
    # "5EnXts8HKLv1o3qhFBGPaoZt1CjMd2g4RtKDpnp3A44xFCGK": "Weight Copier",  # 5FLoWC...SeRv8m
}


def parse_args():
    parser = argparse.ArgumentParser()

    parser.add_argument(
        "netuid",
        type=int,
        help="The uid of the subnet.")

    parser.add_argument(
        "--threshold",
        type=float,
        default=0.0,
        help="The weight threshold above which to print the value. Defaults to 0.")
    
    parser.add_argument(
        "--diff",
        nargs=2,
        help="Diff the weights of two uids or hotkeys rather than printing out all weights.")

    parser.add_argument(
        "--concise",
        action="store_false",
        dest="verbose",
        help="If specified then don't print the actual weight values.")

    parser.add_argument(
        "-l", "--local-subtensor",
        help="Use the specified local subtensor (i.e. la, cali, titan, etc.). "
             "When not specified, use the 'finney' network subtensor."
    )

    return parser.parse_args()


def get_network(name):
    if not name:
        return "finney"
    return name if ":" in name else f"ws://subtensor-{name}.rizzo.network:9944"


def print_weights(owner_uid, owner_hotkey, owner_coldkeys, threshold, metagraph, verbose):
    text = Text()

    text.append(f"\nOwner:\n==========\n{owner_uid} - {owner_hotkey}\n\n\n")
    text.append("Weights:\n==========\n")
    for uid in metagraph.uids[metagraph.validator_permit]:
        name = None
        coldkey = metagraph.coldkeys[uid]
        if coldkey in owner_coldkeys:
            name = "Owner"
            color = 14
        elif coldkey in LEGIT_VALI_COLDKEYS:
            name = LEGIT_VALI_COLDKEYS[coldkey]
            color = 10 if name == "Rizzo" else 12
        elif coldkey in WEIGHT_COPIER_COLDKEYS:
            name = WEIGHT_COPIER_COLDKEYS[coldkey]
            color = 9

        vtrust = metagraph.Tv[uid]
        updated = metagraph.block - metagraph.last_update[uid]
        weights = [(i, float(w)) for i, w in enumerate(metagraph.weights[uid]) if w > threshold]

        if name:
            text.append(f"{name}:\n", style=f"color({color})")
        text.append(f"{uid} - {metagraph.hotkeys[uid]} (Weights: {len(weights)}  vT: {vtrust:.3f}  U: {updated})\n")
        if verbose:
            text.append(str(weights) + "\n")
        text.append("\n")

    Console().print(text)


def print_weight_diffs(uid_a, uid_b, threshold, metagraph, verbose):
    vtrust_a = metagraph.Tv[uid_a]
    vtrust_b = metagraph.Tv[uid_b]
    updated_a = metagraph.block - metagraph.last_update[uid_a]
    updated_b = metagraph.block - metagraph.last_update[uid_b]

    print("Hotkeys:\n=========")
    print(f"{uid_a:<3} - {metagraph.hotkeys[uid_a]} (vT: {vtrust_a:.3f}  U: {updated_a})")
    print(f"{uid_b:<3} - {metagraph.hotkeys[uid_b]} (vT: {vtrust_b:.3f}  U: {updated_b})")
    print("")

    weight_diffs = metagraph.weights[uid_a] - metagraph.weights[uid_b]
    weight_diffs = [(i, float(w)) for i, w in enumerate(weight_diffs) if abs(w) > threshold]

    print("Weight Diffs:\n==============")
    print(f"{len(weight_diffs)} differences\n")
    if verbose:
        for uid, weight_diff in weight_diffs:
            weight_a = metagraph.weights[uid_a][uid]
            weight_b = metagraph.weights[uid_b][uid]
            print(f"{uid}:")
            print(f"{weight_diff}  ({weight_a} - {weight_b})")
            print("")


def get_uid_from_vali_name(metagraph, vali_name):
    for coldkey, name in LEGIT_VALI_COLDKEYS.items():
        if name.lower() == vali_name.lower():
            if coldkey in metagraph.coldkeys:
                return metagraph.coldkeys.index(coldkey)
            else:
                return


def get_diff_uids(diff_a, diff_b, metagraph):
    try:
        uid_a = int(diff_a)
    except ValueError:
        try:
            uid_a = metagraph.hotkeys.index(diff_a)
        except ValueError:
            uid_a = get_uid_from_vali_name(metagraph, diff_a)

    if uid_a is None:
        Console().print(Text(
            f"ERROR: Could not find uid for {diff_a}.",
            style="color(9)"))
        sys.exit(1)

    try:
        uid_b = int(diff_b)
    except ValueError:
        try:
            uid_b = metagraph.hotkeys.index(diff_b)
        except ValueError:
            uid_b = get_uid_from_vali_name(metagraph, diff_b)

    if uid_b is None:
        Console().print(Text(
            f"ERROR: Could not find uid for {diff_b}.",
            style="color(9)"))
        sys.exit(1)

    return uid_a, uid_b


def get_owner(subnet, metagraph):
    owner_hotkey = subnet.owner_hotkey
    owner_coldkey = subnet.owner_coldkey

    if owner_hotkey in metagraph.hotkeys:
        owner_uid = metagraph.hotkeys.index(owner_hotkey)
        owner_coldkeys = set([owner_coldkey, metagraph.coldkeys[owner_uid]])

    elif owner_coldkey in metagraph.coldkeys:
        # Should only happen for subnet 104
        Console().print(Text(
            f"WARNING: Owner hotkey {owner_hotkey} is not in the metagraph.",
            style="color(11)"))
        owner_uid = metagraph.coldkeys.index(owner_coldkey)
        owner_hotkey = metagraph.hotkeys[owner_uid]
        owner_coldkeys = set([owner_coldkey])

    else:
        # Should never happen
        Console().print(Text(
            f"ERROR: Owner hotkey {owner_hotkey} and owner coldkey {owner_coldkey} are not in the metagraph.",
            style="color(9)"))
        owner_uid = None
        owner_hotkey = None
        owner_coldkeys = set()

    return owner_uid, owner_hotkey, owner_coldkeys


def main(args):
    import bittensor

    network = get_network(args.local_subtensor)
    print(f"Connecting to {network}")

    with bittensor.Subtensor(network=network) as subtensor:
        subnet = subtensor.subnet(args.netuid)
        metagraph = subtensor.metagraph(args.netuid, lite=False)

    if args.diff:
        uids = get_diff_uids(*args.diff, metagraph)
        print_weight_diffs(*uids, args.threshold, metagraph, args.verbose)
    else:
        owner_uid, owner_hotkey, owner_coldkeys = get_owner(subnet, metagraph)
        print_weights(owner_uid, owner_hotkey, owner_coldkeys, args.threshold, metagraph, args.verbose)


if __name__ == "__main__":
    try:
        args = parse_args()
        main(args)
    except KeyboardInterrupt as exc:
        import traceback
        exc_list = traceback.format_exception_only(exc)
        exc_text = "\n" + "".join(exc_list).strip("\n")
        print(exc_text)
