#!/usr/bin/env python3

import argparse


def parse_args():
    parser = argparse.ArgumentParser()
    parser.add_argument(
        "netuid",
        type=int,
        help="The uid of the subnet.")

    return parser.parse_args()


def main(args):
    import bittensor

    # cost = bittensor.Subtensor().get_subnet_info(args.netuid).burn
    cost = bittensor.Subtensor().recycle(args.netuid)
    print(f"\nRegistration cost for subnet {args.netuid} = {cost.unit}{cost.tao}\n")


if __name__ == "__main__":
    try:
        args = parse_args()
        main(args)
    except KeyboardInterrupt as exc:
        import traceback
        exc_list = traceback.format_exception_only(exc)
        exc_text = "\n" + "".join(exc_list).strip("\n")
        print(exc_text)
