#!/usr/bin/env python3

# standard imports
import argparse
import asyncio


def parse_args():
    parser = argparse.ArgumentParser()

    parser.add_argument(
        "-s",
        type=int,
        dest="netuids",
        nargs="+",
        help="The uids of the subnets to check. If not specified then all subnets are checked.")

    parser.add_argument(
        "-l", "--local-subtensor",
        help="Use the specified local subtensor (i.e. la, cali, titan, etc.). "
             "When not specified, use the 'finney' network subtensor."
    )

    return parser.parse_args()


def get_network(name):
    if not name:
        return "finney"
    return name if ":" in name else f"ws://subtensor-{name}.rizzo.network:9944"


async def main(args):
    import bittensor

    network = get_network(args.local_subtensor)
    print(f"Connecting to {network}")

    print("")
    print("Subnets with multiple mechanisms")
    print("=================================")

    async with bittensor.AsyncSubtensor(network=network) as subtensor:
        if args.netuids:
            netuids = args.netuids
        else:
            netuids = await subtensor.get_all_subnets_netuid()
            netuids = netuids[1:]

        mechs_list = await asyncio.gather(
            *[
                subtensor.get_mechanism_count(netuid)
                for netuid in netuids
            ]
        )

        # TODO: Only use asyncio.gather to get the emission splits if the
        # number of subnets using multiple mechanisms gets large.
        # emission_list = await asyncio.gather(
        #     *[
        #         subtensor.get_mechanism_emission_split(netuid)
        #         for netuid in netuids
        #     ]
        # )

        for netuid, mechs in zip(netuids, mechs_list):
            if mechs != 1:
                emission = await subtensor.get_mechanism_emission_split(netuid)
                emission = ", ".join([f"{e}%" for e in emission])
                netuid = f"{netuid}:"
                print(f"{netuid:<4} {mechs} ({emission})")

    print("")


if __name__ == "__main__":
    try:
        args = parse_args()
        asyncio.run(main(args))
    except KeyboardInterrupt as exc:
        import traceback
        exc_list = traceback.format_exception_only(exc)
        exc_text = "\n" + "".join(exc_list).strip("\n")
        print(exc_text)
