#!/usr/bin/env python3

import argparse

import bittensor


def parse_args():
    parser = argparse.ArgumentParser()
    parser.add_argument(
        "netuid",
        type=int,
        help="The uid of the subnet.")

    parser.add_argument(
        "-l", "--local-subtensor",
        help="Use the specified local subtensor (i.e. la, cali, titan, etc.). "
             "When not specified, use the 'finney' network subtensor."
    )

    return parser.parse_args()


def get_network(name):
    if not name:
        return "finney"
    return name if ":" in name else f"ws://subtensor-{name}.rizzo.network:9944"


def main():
    args = parse_args()

    network = get_network(args.local_subtensor)
    print(f"Connecting to {network}")

    # cost = bittensor.Subtensor(network=network).subnets.info(args.netuid).burn
    cost = bittensor.Subtensor(network=network).subnets.burn(args.netuid)
    print(f"\nRegistration cost for subnet {args.netuid} = {cost.unit}{cost.tao}\n")


if __name__ == "__main__":
    try:
        main()
    except KeyboardInterrupt as exc:
        import traceback
        exc_list = traceback.format_exception_only(exc)
        exc_text = "\n" + "".join(exc_list).strip("\n")
        print(exc_text)
