#!/usr/bin/env python3

# Standard imports
import argparse
import os
from rich.text import Text
from rich.console import Console
import sys

# Bittensor import
import bittensor

# Add local helper_scripts dir to path for importing helper_scripts_common.py
sys.path = [os.path.dirname(__file__)] + sys.path

# Local imports
from helper_scripts_common import (
    get_lite_subtensor_network,
    LEGIT_VALI_COLDKEYS,
    WEIGHT_COPIER_COLDKEYS,
)


def parse_args():
    parser = argparse.ArgumentParser()

    parser.add_argument(
        "-s",
        dest="netuid",
        type=int,
        required=True,
        help="The uid of the subnet.")

    parser.add_argument(
        "--mechid",
        type=int,
        default=0,
        help="The mechanism to check. Defaults to mechid 0.")

    parser.add_argument(
        "--target-uids",
        nargs="+",
        type=int,
        help="When specified, only display the weights for the specified target uids."
    )

    parser.add_argument(
        "--threshold",
        type=float,
        default=0.0,
        help="The weight threshold above which to print the value. Defaults to 0.")
    
    parser.add_argument(
        "--diff",
        nargs=2,
        help="Diff the weights of two uids or hotkeys rather than printing out all weights.")

    parser.add_argument(
        "--concise",
        action="store_false",
        dest="verbose",
        help="If specified then don't print the actual weight values.")

    parser.add_argument(
        "--print-coldkeys",
        action="store_true",
        help="If specified then print the validators' coldkeys instead of their hotkeys. "
             "This arg does not apply to the --diff printout.")

    parser.add_argument(
        "-l", "--local-subtensor",
        nargs="?",
        default=False,
        help="Use the specified local subtensor (i.e. la, cali, titan, etc.). "
             "When not specified, use the 'finney' network subtensor."
    )

    return parser.parse_args()


class GetValidatorWeights:
    def __init__(self, args):
        self._netuid = args.netuid
        self._mechid = args.mechid
        self._diff = args.diff
        self._target_uids = args.target_uids
        self._threshold = args.threshold
        self._verbose = args.verbose
        self._print_coldkeys = args.print_coldkeys
        self._local_subtensor = args.local_subtensor

        self._run()

    def _run(self):
        network = get_lite_subtensor_network(self._local_subtensor)
        print(f"Connecting to {network}")
    
        with bittensor.Subtensor(network=network) as subtensor:
            self._subtensor = subtensor.at(subtensor.block)

            self._block = self._subtensor.block
            self._metagraph = self._subtensor.subnets.metagraph(self._netuid, commitments=False)
            self._weights = self._subtensor.weights.weights(netuid=self._netuid, mechid=self._mechid)
            self._vtrusts = self._subtensor.query(
                bittensor.storage.SubtensorModule.ValidatorTrust,
                params=[self._netuid]
            )
            last_update_index = self._mechid * bittensor.settings.GLOBAL_MAX_SUBNET_COUNT + self._netuid
            self._last_updates = self._subtensor.query(
                bittensor.storage.SubtensorModule.LastUpdate,
                params=[last_update_index]
            )

            if self._diff:
                self._print_weight_diffs()
            else:
                self._print_weights()

    def _print_weights(self):
        owner_uid, owner_hotkey, owner_coldkeys = self._get_owner()

        text = Text()
        if self._print_coldkeys:
            owner_keys = f"({', '.join(owner_coldkeys)})" if len(owner_coldkeys) > 1 else owner_coldkeys[0]
        else:
            owner_keys = owner_hotkey
        text.append(f"\nOwner:\n==========\n{owner_uid} - {owner_keys}\n\n\n")
        text.append("Weights:\n==========\n")

        for validator in self._metagraph.validators:
            uid = validator.uid
            coldkey = validator.coldkey
            hotkey = validator.hotkey

            name = None
            if coldkey in owner_coldkeys:
                name = "Owner"
                color = 14
            elif coldkey in LEGIT_VALI_COLDKEYS:
                name = LEGIT_VALI_COLDKEYS[coldkey]
                color = 10 if name == "Rizzo" else 12
            elif coldkey in WEIGHT_COPIER_COLDKEYS:
                name = WEIGHT_COPIER_COLDKEYS[coldkey]
                color = 9

            vtrust =  self._get_vtrust(uid)
            updated = self._get_updated(uid)
            weights = self._get_weights(uid)
            num_weights = len(weights)

            if name:
                text.append(f"{name}:\n", style=f"color({color})")
            key = coldkey if self._print_coldkeys else hotkey
            text.append(f"{uid} - {key} (Weights: {num_weights}  vT: {vtrust:.3f}  U: {updated})\n")
            if self._verbose:
                text.append(str(weights) + "\n")
            text.append("\n")

        Console().print(text)

    def _print_weight_diffs(self):
        uid_a, uid_b = self._get_diff_uids()

        vtrust_a = self._get_vtrust(uid_a)
        vtrust_b = self._get_vtrust(uid_b)
        updated_a = self._get_updated(uid_a)
        updated_b = self._get_updated(uid_b)

        print("Hotkeys:\n=========")
        print(f"{uid_a:<3} - {self._metagraph.hotkeys[uid_a]} (vT: {vtrust_a:.3f}  U: {updated_a})")
        print(f"{uid_b:<3} - {self._metagraph.hotkeys[uid_b]} (vT: {vtrust_b:.3f}  U: {updated_b})")
        print("")

        weight_diffs = self._get_weight_diffs(uid_a, uid_b)

        print("Weight Diffs:\n==============")
        print(f"{len(weight_diffs)} differences\n")
        if self._verbose:
            for uid, weight_diff, weight_a, weight_b in weight_diffs:
                print(f"{uid}:")
                print(f"{weight_diff}  ({weight_a} - {weight_b})")
                print("")

    def _get_owner(self):
        owner_hotkey = self._metagraph.owner_hotkey
        owner_coldkey = self._metagraph.owner_coldkey

        if owner_hotkey in self._metagraph.hotkeys:
            owner_uid = self._metagraph.hotkeys.index(owner_hotkey)
            owner_coldkeys = set([owner_coldkey, self._metagraph.coldkeys[owner_uid]])

        elif owner_coldkey in self._metagraph.coldkeys:
            # Should only happen for subnet 104
            Console().print(Text(
                f"WARNING: Owner hotkey {owner_hotkey} is not registered.",
                style="color(11)"))
            owner_uid = self._metagraph.coldkeys.index(owner_coldkey)
            owner_hotkey = self._metagraph.hotkeys[owner_uid]
            owner_coldkeys = set([owner_coldkey])

        else:
            # Should never happen
            Console().print(Text(
                f"ERROR: Owner hotkey {owner_hotkey} and owner coldkey {owner_coldkey} "
                "are not registered.", style="color(9)"))
            owner_uid = None
            owner_hotkey = None
            owner_coldkeys = set()

        owner_coldkeys = list(owner_coldkeys)

        return owner_uid, owner_hotkey, owner_coldkeys

    def _get_diff_uids(self):
        uids = []

        for diff_val in self._diff:
            try:
                uid = int(diff_val)
            except ValueError:
                try:
                    uid = self._metagraph.hotkeys.index(diff_val)
                except ValueError:
                    uid = self._get_uid_from_vali_name(diff_val)

            if uid is None:
                Console().print(Text(
                    f"ERROR: Could not find uid for {diff_val}.",
                    style="color(9)"))
                sys.exit(1)

            uids.append(uid)

        return uids

    def _get_uid_from_vali_name(self, vali_name):
        for coldkey, name in LEGIT_VALI_COLDKEYS.items():
            if name.lower() == vali_name.lower():
                if coldkey in self._metagraph.coldkeys:
                    return self._metagraph.coldkeys.index(coldkey)
                return None

    def _get_vtrust(self, uid):
        return self._vtrusts[uid] / bittensor.settings.U16_MAX

    def _get_updated(self, uid):
        return self._block - self._last_updates[uid]

    def _get_weights(self, uid):
        def filter_weight(i, w):
            if not w or w < self._threshold:
                return False
            if self._target_uids and i not in self._target_uids:
                return False
            return True

        weights = [(i, w) for i, w in self._weights.get(uid, {}).items() if filter_weight(i, w)]
        weights.sort(key=lambda w: w[0])

        return weights

    def _get_weight_diffs(self, uid_a, uid_b):
        weight_diffs = []

        for uid in sorted(set(self._weights.get(uid_a, {})) | set(self._weights.get(uid_b, {}))):
            if self._target_uids and uid not in self._target_uids:
                continue

            weight_a = self._get_weight(uid_a, uid)
            weight_b = self._get_weight(uid_b, uid)
            diff = weight_a - weight_b
            if not diff or abs(diff) < self._threshold:
                continue

            weight_diffs.append((uid, diff, weight_a, weight_b))

        return weight_diffs

    def _get_weight(self, source_uid, target_uid):
        return self._weights[source_uid].get(target_uid, 0.0)

def main():
    args = parse_args()

    if args.diff and args.print_coldkeys:
        Console().print(Text(
            "ERROR: The --print-coldkeys arg does not apply when printing the weight diffs.",
            style="color(9)"))
        return

    GetValidatorWeights(args)


if __name__ == "__main__":
    try:
        main()
    except KeyboardInterrupt as exc:
        import traceback
        exc_list = traceback.format_exception_only(exc)
        exc_text = "\n" + "".join(exc_list).strip("\n")
        print(exc_text)
