#!/usr/bin/env python3

# Standard imports
import argparse
import os
import sys

# Bittensor import
import bittensor

# Add local helper_scripts dir to path for importing helper_scripts_common.py
sys.path = [os.path.dirname(__file__)] + sys.path

# Local imports
from helper_scripts_common import get_lite_subtensor_network


def parse_args():
    parser = argparse.ArgumentParser()
    parser.add_argument(
        "netuid",
        type=int,
        help="The uid of the subnet.")

    parser.add_argument(
        "-l", "--local-subtensor",
        nargs="?",
        default=False,
        help="Use the specified local subtensor (i.e. la, cali, titan, etc.). "
             "When not specified, use the 'finney' network subtensor."
    )

    return parser.parse_args()


def main():
    args = parse_args()

    network = get_lite_subtensor_network(args.local_subtensor)
    print(f"Connecting to {network}")

    # cost = bittensor.Subtensor(network=network).subnets.info(args.netuid).burn
    cost = bittensor.Subtensor(network=network).subnets.burn(args.netuid)
    print(f"\nRegistration cost for subnet {args.netuid} = {cost.unit}{cost.tao}\n")


if __name__ == "__main__":
    try:
        main()
    except KeyboardInterrupt as exc:
        import traceback
        exc_list = traceback.format_exception_only(exc)
        exc_text = "\n" + "".join(exc_list).strip("\n")
        print(exc_text)
