#!/usr/bin/env python3

# Reference docs for calculating alpha price
# https://docs.taostats.io/docs/alpha-emission
# https://docs.taostats.io/docs/subnet-pools

# Standard imports
import argparse
import asyncio
from dataclasses import dataclass, field
import os
from rich.text import Text
from rich.console import Console
import sys

# Bittensor import
import bittensor

# Add local helper_scripts dir to path for importing helper_scripts_common.py
sys.path = [os.path.dirname(__file__)] + sys.path

# Local imports
from helper_scripts_common import (
    get_lite_subtensor_network,
    LEGIT_VALI_COLDKEYS,
    WEIGHT_COPIER_COLDKEYS,
)


@dataclass
class StakeData:
    @dataclass
    class AlphaTuple:
        stake: float
        price: float

    stake_in_alpha: dict = field(default_factory=dict)
    stake_in_tao: float = 0.0


def parse_args():
    parser = argparse.ArgumentParser()

    # parser.add_argument(
    #     "type",
    #     choices=["stake", "reg", "vt", "vtea"],
    #     help="Only display the top validators up to this number. For example, "
    #             "--top 50 shows only the top 50 validators.")

    parser.add_argument(
        "--top",
        type=int,
        help="Only display the top validators up to this number. For example, "
             "--top 50 shows only the top 50 validators.")

    parser.add_argument(
        "-l", "--local-subtensor",
        nargs="?",
        default=False,
        help="Use the specified local subtensor (i.e. la, cali, titan, etc.). "
             "When not specified, use the 'finney' network subtensor."
    )

    return parser.parse_args()


async def get_metagraphs():
    network = get_lite_subtensor_network(args.local_subtensor)
    print(f"Connecting to {network}")

    async with bittensor.Subtensor(network=network) as subtensor:
        # Get a snapshot of the subtensor at the current block so everything is in sync
        # in case data gathering take multiple blocks.
        block = await subtensor.block()
        subtensor_snapshot = await subtensor.at(block)

        # Get all subnets
        subnets = await subtensor_snapshot.subnets.all()
        netuids = [sn.netuid for sn in subnets][1:]

        # Get the metagraph for each netuid
        metagraphs = await asyncio.gather(
            *[
                subtensor_snapshot.subnets.metagraph(netuid, commitments=False)
                for netuid in netuids
            ]
        )

    return metagraphs


def update_validators_stake(validators_stake, metagraph):
    alpha_price = metagraph.price
    for validator in metagraph.validators:
        stake_in_alpha = validator.total_stake.amount
        stake_in_tao = stake_in_alpha * alpha_price

        stake_data = validators_stake.setdefault(validator.coldkey, StakeData())
        stake_data.stake_in_alpha[metagraph.netuid] = \
            StakeData.AlphaTuple(stake=stake_in_alpha, price=alpha_price)
        stake_data.stake_in_tao += stake_in_tao


def print_stake_rankings(validators_stake, num_total):
    def get_tao_stake(coldkey):
        return validators_stake[coldkey].stake_in_tao

    print("")
    text = Text()

    for rank, coldkey in enumerate(reversed(sorted(validators_stake, key=get_tao_stake)), 1):
        if rank > num_total:
            break

        text.append(f"{rank:<2} - ")
        if coldkey in LEGIT_VALI_COLDKEYS:
            name = LEGIT_VALI_COLDKEYS[coldkey]
            color = 10 if name == "Rizzo" else 12
            style = f"color({color})"
        elif coldkey in WEIGHT_COPIER_COLDKEYS:
            name = WEIGHT_COPIER_COLDKEYS[coldkey]
            color = 9
            style = f"color({color})"
        else:
            name = coldkey[:6] + "..." + coldkey[-6:]
            style = None
        text.append(f"{name:<15}", style=style)

        stake_data = validators_stake[coldkey]
        text.append("  --  ")
        text.append(f"{stake_data.stake_in_tao:.3f}\n", style=style)

    Console().print(text)


async def main(args):
    metagraphs = await get_metagraphs()

    validators_stake = {}
    for metagraph in metagraphs:
        update_validators_stake(validators_stake, metagraph)

    num_total = args.top or len(validators_stake)
    print_stake_rankings(validators_stake, num_total)


if __name__ == "__main__":
    try:
        args = parse_args()
        asyncio.run(main(args))
    except KeyboardInterrupt as exc:
        import traceback
        exc_list = traceback.format_exception_only(exc)
        exc_text = "\n" + "".join(exc_list).strip("\n")
        print(exc_text)
