#!/usr/bin/env python3

import argparse


def parse_args():
    parser = argparse.ArgumentParser()

    parser.add_argument(
        "netuid",
        type=int,
        help="The uid of the subnet.")

    parser.add_argument(
        "-u", "--uids",
        type=int,
        nargs="+",
        required=True,
        help="The uids of the validators for which to print weights.")

    parser.add_argument(
        "--threshold",
        type=float,
        default=0.0,
        help="The weight threshold above which to print the weight values. Defaults to 0.")

    parser.add_argument(
        "--num",
        type=int,
        default=24,
        help="The number of intervals to print. It will print one more value than this arg "
             "since it also prints the curent weights.")

    parser.add_argument(
        "--interval",
        type=float,
        default=1.0,
        help="The interval at which to print weights, in hours.")

    parser.add_argument(
        "-l", "--local-subtensor",
        help="Use the specified local subtensor (i.e. la, cali, titan, etc.). "
             "When not specified, use the 'finney' network subtensor."
    )

    return parser.parse_args()


def get_formatted_time(total_time):
    # Get hours
    h = total_time/3600
    hours = int(h)

    # Get minutes
    remainder = round((h - hours)*3600)
    m = remainder/60
    minutes = int(m)

    # Get seconds
    seconds = round((m - minutes)*60)

    # Get formatted time
    formatted_time = [f"{hours} hours"] if hours else []
    if minutes:
        formatted_time.append(f"{minutes} minutes")
    if seconds or not formatted_time:
        formatted_time.append(f"{seconds} seconds")
    formatted_time = ", ".join(formatted_time)

    return formatted_time


def get_network(name):
    if not name:
        return "archive"
    return name if ":" in name else f"ws://subtensor-{name}.rizzo.network:9944"


def print_weights(subtensor, args):
    block_interval = int(round(args.interval * 300))  # Interval is in hours. 300 blocks per hour.
    num_weight_samples = args.num + 1
    print(f"\nBlock interval: {block_interval} ({args.interval} hours)\n")

    for sample_num in range(num_weight_samples):
        block_diff = (block_interval * sample_num)
        time_diff = get_formatted_time(block_diff * 12)  # 12 seconds per block.

        block = subtensor.block - block_diff
        metagraph = subtensor.metagraph(args.netuid, block=block, lite=False)

        print(f"Time: {time_diff}")
        for uid in args.uids:
            vtrust = metagraph.Tv[uid]
            updated = metagraph.block - metagraph.last_update[uid]
            weights = [(i, float(w)) for i, w in enumerate(metagraph.weights[uid]) if float(w) > args.threshold]
            print(f"uid {uid} (vT: {vtrust:.3f}  U: {updated}):\n{weights}\n")
        print("\n")


def main(args):
    import bittensor

    network = get_network(args.local_subtensor)
    print(f"Connecting to {network}")

    with bittensor.Subtensor(network=network) as subtensor:
        print_weights(subtensor, args)


if __name__ == "__main__":
    try:
        args = parse_args()
        main(args)
    except KeyboardInterrupt as exc:
        import traceback
        exc_list = traceback.format_exception_only(exc)
        exc_text = "\n" + "".join(exc_list).strip("\n")
        print(exc_text)
