#!/usr/bin/env python3

# Standard imports
import argparse
import asyncio
import os
import sys

# Bittensor import
import bittensor

# Add local helper_scripts dir to path for importing helper_scripts_common.py
sys.path = [os.path.dirname(__file__)] + sys.path

# Local imports
from helper_scripts_common import get_formatted_time


def parse_args():
    parser = argparse.ArgumentParser()

    parser.add_argument(
        "netuid",
        type=int,
        help="The uid of the subnet.")

    parser.add_argument(
        "--mechid",
        type=int,
        default=0,
        help="The mechanism to check. Defaults to mechid 0.")

    parser.add_argument(
        "-u", "--uids",
        type=int,
        nargs="+",
        required=True,
        help="The uids of the validators for which to print weights.")

    parser.add_argument(
        "--target-uids",
        nargs="+",
        type=int,
        help="When specified, only display the weights for the specified target uids."
    )

    parser.add_argument(
        "--threshold",
        type=float,
        default=0.0,
        help="The weight threshold above which to print the weight values. Defaults to 0.")

    parser.add_argument(
        "--num",
        type=int,
        default=24,
        help="The number of intervals to print. It will print one more value than this arg "
             "since it also prints the curent weights.")

    parser.add_argument(
        "--interval",
        type=float,
        default=1.0,
        help="The interval at which to print weights, in hours.")

    parser.add_argument(
        "--concise",
        action="store_false",
        dest="verbose",
        help="If specified then don't print the actual weight values.")

    parser.add_argument(
        "-l", "--local-subtensor",
        help="Use the specified local subtensor (i.e. la, cali, titan, etc.). "
             "When not specified, use the 'finney' network subtensor."
    )

    return parser.parse_args()


def get_network(name):
    if not name:
        return "archive"
    return name if ":" in name else f"ws://subtensor-{name}.rizzo.network:9944"


async def _get_chain_data_at_block(subtensor, netuid, mechid, block):
    snapshot = await subtensor.at(block)
    weights = await snapshot.weights.weights(netuid=netuid, mechid=mechid)
    vtrusts = await snapshot.query(
        bittensor.storage.SubtensorModule.ValidatorTrust, params=[netuid]
    )
    last_update_index = mechid * bittensor.settings.GLOBAL_MAX_SUBNET_COUNT + netuid
    last_updates = await snapshot.query(
        bittensor.storage.SubtensorModule.LastUpdate, params=[last_update_index]
    )
    return (weights, vtrusts, last_updates)


async def main():
    args = parse_args()

    network = get_network(args.local_subtensor)
    print(f"Connecting to {network}")

    block_interval = int(round(args.interval * 300))  # Interval is in hours. 300 blocks per hour.
    num_weight_samples = args.num + 1
    block_diffs = [block_interval * n for n in range(num_weight_samples)]
    print(f"\nBlock interval: {block_interval} ({args.interval} hours)\n")

    async with bittensor.Subtensor(network=network) as subtensor:
        current_block = await subtensor.block()

        chain_data = await asyncio.gather(
            *[
                _get_chain_data_at_block(
                    subtensor, args.netuid, args.mechid, (current_block - block_diff)
                ) for block_diff in block_diffs
            ]
        )

    def filter_weight(i, w):
        if not w or w < args.threshold:
            return False
        if args.target_uids and i not in args.target_uids:
            return False
        return True

    for sample_num in range(num_weight_samples):
        (all_weights, vtrusts, last_updates) = chain_data[sample_num]
        block_diff = block_diffs[sample_num]
        block = current_block - block_diff
        time_diff = get_formatted_time(block_diff * 12)  # 12 seconds per block.

        print(f"Time: {time_diff}")
        for uid in args.uids:
            vtrust = vtrusts[uid] / bittensor.settings.U16_MAX
            updated = block - last_updates[uid]
            print(f"uid {uid} (vT: {vtrust:.3f}  U: {updated})")
            if args.verbose:
                weights = [(i, w) for i, w in all_weights.get(uid, {}).items() if filter_weight(i, w)]
                weights.sort(key=lambda w: w[0])
                print(f"{weights}\n")
        print("\n")


if __name__ == "__main__":
    try:
        asyncio.run(main())
    except KeyboardInterrupt as exc:
        import traceback
        exc_list = traceback.format_exception_only(exc)
        exc_text = "\n" + "".join(exc_list).strip("\n")
        print(exc_text)
