#!/usr/bin/env python3

import argparse
import asyncio


def parse_args():
    parser = argparse.ArgumentParser()

    parser.add_argument(
        "netuid",
        type=int,
        help="The uid of the subnet.")

    parser.add_argument(
        "-u", "--uids",
        type=int,
        nargs="+",
        required=True,
        help="The uids of the validators for which to print weights.")

    parser.add_argument(
        "--target-uids",
        nargs="+",
        type=int,
        help="When specified, only display the weights for the specified target uids."
    )

    parser.add_argument(
        "--threshold",
        type=float,
        default=0.0,
        help="The weight threshold above which to print the weight values. Defaults to 0.")

    parser.add_argument(
        "--num",
        type=int,
        default=24,
        help="The number of intervals to print. It will print one more value than this arg "
             "since it also prints the curent weights.")

    parser.add_argument(
        "--interval",
        type=float,
        default=1.0,
        help="The interval at which to print weights, in hours.")

    parser.add_argument(
        "--concise",
        action="store_false",
        dest="verbose",
        help="If specified then don't print the actual weight values.")

    parser.add_argument(
        "-l", "--local-subtensor",
        help="Use the specified local subtensor (i.e. la, cali, titan, etc.). "
             "When not specified, use the 'finney' network subtensor."
    )

    return parser.parse_args()


def get_formatted_time(total_time):
    # Get hours
    h = total_time/3600
    hours = int(h)

    # Get minutes
    remainder = round((h - hours)*3600)
    m = remainder/60
    minutes = int(m)

    # Get seconds
    seconds = round((m - minutes)*60)

    # Get formatted time
    formatted_time = [f"{hours} hours"] if hours else []
    if minutes:
        formatted_time.append(f"{minutes} minutes")
    if seconds or not formatted_time:
        formatted_time.append(f"{seconds} seconds")
    formatted_time = ", ".join(formatted_time)

    return formatted_time


def get_network(name):
    if not name:
        return "archive"
    return name if ":" in name else f"ws://subtensor-{name}.rizzo.network:9944"


async def main(args):
    import bittensor

    network = get_network(args.local_subtensor)
    print(f"Connecting to {network}")

    block_interval = int(round(args.interval * 300))  # Interval is in hours. 300 blocks per hour.
    num_weight_samples = args.num + 1
    block_diffs = [block_interval * n for n in range(num_weight_samples)]
    print(f"\nBlock interval: {block_interval} ({args.interval} hours)\n")

    async with bittensor.AsyncSubtensor(network=network) as subtensor:
        current_block = await subtensor.block
        metagraphs = await asyncio.gather(
            *[
                subtensor.metagraph(args.netuid, block=(current_block - block_diff), lite=False)
                for block_diff in block_diffs
            ]
        )

    for sample_num in range(num_weight_samples):
        metagraph = metagraphs[sample_num]
        block_diff = block_diffs[sample_num]
        time_diff = get_formatted_time(block_diff * 12)  # 12 seconds per block.

        print(f"Time: {time_diff}")
        for uid in args.uids:
            vtrust = metagraph.Tv[uid]
            updated = metagraph.block - metagraph.last_update[uid]
            print(f"uid {uid} (vT: {vtrust:.3f}  U: {updated})")
            if args.verbose:
                weights = [(i, float(w)) for i, w in enumerate(metagraph.weights[uid]) if float(w) > args.threshold]
                if args.target_uids:
                    weights = [w for w in weights if w[0] in args.target_uids]
                print(f"{weights}\n")
        print("\n")


if __name__ == "__main__":
    try:
        args = parse_args()
        asyncio.run(main(args))
    except KeyboardInterrupt as exc:
        import traceback
        exc_list = traceback.format_exception_only(exc)
        exc_text = "\n" + "".join(exc_list).strip("\n")
        print(exc_text)
