#!/usr/bin/env python3

# standard imports
import argparse
from dataclasses import dataclass, asdict
import json
import multiprocessing
import os
import sys
import time

# Set path to import local modules
sys.path = [os.path.dirname(__file__)] + sys.path

from subtensor_constants import (
    LOCAL_TIMEZONE,
    JSON_FILE_NAME,
    FINNEY_BLOCK_FILE_NAME,
    TIMESTAMP_FILE_NAME,
    LOCAL_SUBTENSORS,
    FINNEY_INTERVAL,
)
from subtensor_utils import (
    FinneyBlockData,
    format_time
)


mp_queue = multiprocessing.Queue()


@dataclass
class SubtensorData:
    name: str
    block_diff: int | None
    error: str | None


def _parse_args():
    parser = argparse.ArgumentParser()

    parser.add_argument(
        "-j", "--json-folder",
        help="The json folder in which to write the json files. If this is specified "
             "then a json is written containing each subtensor's status. If not "
             "specified then each subtensor's status is printed to stdout."
    )

    parser.add_argument(
        "-f", "--finney-block-folder",
        help="The json folder in which to read the finney block json file. If this "
                "is specified then the finney block is read from the file. If not "
                "specified then the finney block is obtained from the subtensor."
    )

    parser.add_argument(
        "-i", "--interval",
        type=float,
        default=0,
        help="The number of minutes between validator data gathering. If 0 or not "
             "specified then the data is gathered only once."
    )

    return parser.parse_args()


# TODO - This is ridiculous. The timestamp just needs to be in the subtensor_status.json file
def write_timestamp(json_folder):
    timestamp_file = os.path.join(json_folder, TIMESTAMP_FILE_NAME)

    os.environ["TZ"] = LOCAL_TIMEZONE
    time.tzset()

    data_file = os.path.join(json_folder, JSON_FILE_NAME)
    if os.path.isfile(data_file):
        file_time = os.path.getmtime(data_file)
    else:
        bittensor.logging.error(f"Can't get timestamp. Json file does not exist: {data_file}")
        file_time = 0

    timestamp = {
        "display_time": time.ctime(file_time),
        "actual_time": int(file_time),
    }

    # First remove the existing timestamp file
    if os.path.isfile(timestamp_file):
        bittensor.logging.info(f"Removing {timestamp_file}")
        os.unlink(timestamp_file)

    # Then write the new timestamp file
    bittensor.logging.info(f"Writing timestamp file: {timestamp_file}")
    with open(timestamp_file, "w") as fd:
        json.dump(timestamp, fd)


def write_json_file(subtensor_data, json_folder):
    json_file = os.path.join(json_folder, JSON_FILE_NAME)

    # Get a serializable version of the data
    subtensor_json_data = []
    for subtensor in subtensor_data:
        subtensor_json_data.append(asdict(subtensor))

    # First remove the existing json file
    if os.path.isfile(json_file):
        bittensor.logging.info(f"Removing {json_file}")
        os.unlink(json_file)

    # Then write the new data json file
    bittensor.logging.info(f"\nWriting data to file: {json_file}")
    with open(json_file, "w") as fd:
        json.dump(subtensor_json_data, fd, indent=4)

    # Write the timestamp file
    write_timestamp(json_folder)


def print_subtensor_statuses(subtensor_data):
    from rich.console import Console
    from rich.text import Text

    red = "9"
    green = "10"
    yellow = "11"
    name_padding = max([len(s.name) for s in subtensor_data])

    console = Console()
    text = Text()

    for subtensor in subtensor_data:
        subtensor_network = f"{subtensor.name}".ljust(name_padding)

        if subtensor.error:
            subtensor_status = subtensor.error
            text_color = red
        elif subtensor.block_diff is None:
            subtensor_status = "Unknown"
            text_color = yellow
        elif subtensor.block_diff > 0:
            subtensor_status = f"{subtensor.block_diff} blocks behind finney"
            text_color = red
        else:
            subtensor_status = "Operational"
            text_color = green

        text_style = f"color({text_color})"
        text.append("\n")
        text.append(
            f"{subtensor_network} - {subtensor_status}",
            style=text_style
        )

    text.append("\n")
    console.print(text)


def get_subtensor_block(network):
    # Testing multiprocessing module to see if it keeps the bittensor
    # function calls from lagging over time.
    try:
        with bittensor.Subtensor(network=network) as subtensor:
            mp_queue.put(subtensor.block)
    except Exception as err:
        mp_queue.put(f"{type(err).__name__}: {err}")


def run_in_subprocess(network):
    # Testing multiprocessing module to see if it keeps the bittensor
    # function calls from lagging over time.
    args = [network]
    with multiprocessing.Pool(processes=1) as pool:
        pool.apply(get_subtensor_block, args)

    return mp_queue.get()


def get_finney_block_from_json_file(finney_block_folder):
    json_file = os.path.join(finney_block_folder, FINNEY_BLOCK_FILE_NAME)

    if not os.path.isfile(json_file):
        bittensor.logging.error(f"Finney block json file does not exist: {json_file}")
        return None

    with open(json_file, "r") as fd:
        finney_block_dict = json.load(fd)
    finney_block_data = FinneyBlockData(**finney_block_dict)

    if finney_block_data.block is None:
        bittensor.logging.error("Finney block json file does not contain the "
                                f"finney block: {json_file}")
        return None

    block_diff = round((time.time() - finney_block_data.time) / 12)  # seconds per block
    return finney_block_data.block + block_diff


def get_finney_block_from_subtensor():
    result = run_in_subprocess("finney")
    try:
        return int(result)
    except ValueError:
        bittensor.logging.error("Failed to get finney block.")
        bittensor.logging.error(result)
        return None


def get_finney_block(options):
    if options.finney_block_folder:
        bittensor.logging.info("Getting finney block from json file.")
        return get_finney_block_from_json_file(options.finney_block_folder)
    else:
        bittensor.logging.info("Getting finney block from subtensor.")
        return get_finney_block_from_subtensor()


def main(options):
    bittensor.logging.enable_info()
    minutes_until_get_finney_block = 0
    interval_seconds = round(options.interval * 60)

    while True:
        bittensor.logging.info("Getting subtensor statuses.")
        start_time = time.time()
        subtensor_data = []

        if minutes_until_get_finney_block <= 0:
            finney_block = get_finney_block(options)
            minutes_until_get_finney_block = FINNEY_INTERVAL
        else:
            bittensor.logging.info(
                "Not getting finney block. "
                f"{minutes_until_get_finney_block} minutes left."
            )

        delay_start = time.time()
        for subtensor_name in LOCAL_SUBTENSORS:
            network = subtensor_name.split(maxsplit=1)[0]
            bittensor.logging.info(f"Getting block for {network}")
            result = run_in_subprocess(network)
            try:
                block = int(result)
            except ValueError:
                block = None
                error = result

            if block is not None:
                delay_blocks = int((time.time() - delay_start) / 12)
                if finney_block is not None:
                    block_diff = int(finney_block - block) + delay_blocks
                else:
                    block_diff = None
                error = None
            else:
                block_diff = None

            subtensor_data.append(
                SubtensorData(
                    name=subtensor_name,
                    block_diff=block_diff,
                    error=error,
                )
            )

        if options.json_folder:
            write_json_file(subtensor_data, options.json_folder)
        else:
            print_subtensor_statuses(subtensor_data)

        total_seconds = round(time.time() - start_time)
        total_time_formatted = format_time(total_seconds)
        bittensor.logging.info(f"Subnet data gathering took {total_time_formatted}.\n")

        # Only gather the data once.
        if not interval_seconds:
            break

        wait_seconds = interval_seconds - total_seconds
        if wait_seconds > 0:
            wait_time_formatted = format_time(wait_seconds)
            bittensor.logging.info(f"Waiting {wait_time_formatted}.")
            time.sleep(wait_seconds)
        else:
            bittensor.logging.warning(
                f"Processing took {total_seconds} seconds which is longer "
                f"than {interval_seconds} seconds. Not waiting."
            )

        minutes_until_get_finney_block -= options.interval
        if finney_block is not None:
            finney_block += options.interval * 5  # 5 blocks per minute


if __name__ == "__main__":
    try:
        options = _parse_args()

        # Bittensor import
        import bittensor

        main(options)
    except KeyboardInterrupt as exc:
        import traceback
        exc_list = traceback.format_exception_only(exc)
        exc_text = "\n" + "".join(exc_list).strip("\n")
        print(exc_text)
