#!/usr/bin/env python3

# standard imports
import argparse
from dataclasses import asdict
import json
import os
import shlex
import subprocess
import sys
import time

# Set path to import local modules
sys.path = [os.path.dirname(__file__)] + sys.path

from subtensor_constants import FINNEY_BLOCK_FILE_NAME
from subtensor_utils import (
    FinneyBlockData,
    format_time,
    logger,
)


def _parse_args():
    parser = argparse.ArgumentParser()

    parser.add_argument(
        "-j", "--json-folder",
        required=True,
        help="The json folder in which to write the finney block json file."
    )

    parser.add_argument(
        "-t", "--transfer-to-jerky",
        help="The json folder on the jerky (2292) VM to transfer the finney block json file."
    )

    return parser.parse_args()


def get_finney_block():
    # Testing multiprocessing module to see if it keeps the bittensor
    # function calls from lagging over time.
    try:
        with bittensor.Subtensor(network="finney") as subtensor:
            return subtensor.block
    except Exception as err:
        return f"{type(err).__name__}: {err}"


def write_finney_block_file(finney_block_data, json_folder):
    json_file = os.path.join(json_folder, FINNEY_BLOCK_FILE_NAME)

    # First remove existing file
    if os.path.isfile(json_file):
        logger.info("Removing: %s", json_file)
        os.unlink(json_file)

    # Then write the new  file
    logger.info("\nWriting data to file: %s", json_file)
    with open(json_file, "w") as fd:
        json.dump(asdict(finney_block_data), fd, indent=4)

    return json_file


def transfer_to_jerky(source_file, dest_folder):
    # This only works from Sol's home computer
    transfer_command = [
        "/home/bhorvat/venv-bittensor/bin/python",
        "/home/bhorvat/bittensor/scripts/git_projects/Sol-BT-Scripts/file_transfer/ssh/file_transfer_ssh",
        "--ssh-key", "/home/bhorvat/.ssh/bh_wsl_key",
        "--host", "datacenter1.rizzo.network",
        "--port", "2292",
        "--user", "rizzo",
        "--send",
        "--sources", source_file,
        "--dest", dest_folder,
    ]

    logger.info("Running transfer command: %s", shlex.join(transfer_command))
    try:
        subprocess.run(transfer_command, check=True)
    except subprocess.CalledProcessError as exc:
        logger.error("Command failed with error: %s", exc)
    else:
        logger.info("Command succeeded.")


def main(options):
    logger.info("Getting finney block.")

    start_time = time.time()

    result = get_finney_block()
    finney_block_time = int(time.time())
    try:
        finney_block = int(result)
    except ValueError:
        finney_block = None
        logger.error("Failed to get finney block.")
        logger.error(result)

    finney_block_data = FinneyBlockData(
        block=finney_block,
        time=finney_block_time,
    )

    total_seconds = round(time.time() - start_time)
    total_time_formatted = format_time(total_seconds)
    logger.info("Finney block gathering took %s.\n", total_time_formatted)

    json_file = write_finney_block_file(finney_block_data, options.json_folder)
    if options.transfer_to_jerky:
        transfer_to_jerky(json_file, options.transfer_to_jerky)


if __name__ == "__main__":
    try:
        options = _parse_args()

        # Bittensor import
        import bittensor

        main(options)
    except KeyboardInterrupt as exc:
        import traceback
        exc_list = traceback.format_exception_only(exc)
        exc_text = "\n" + "".join(exc_list).strip("\n")
        print(exc_text)
