#!/usr/bin/env python3

# standard imports
import argparse
from dataclasses import asdict
import json
import os
import sys
import time

# Set path to import local modules
sys.path = [os.path.dirname(__file__)] + sys.path

from subtensor_constants import FINNEY_BLOCK_FILE_NAME
from subtensor_utils import (
    FinneyBlockData,
    format_time,
)


def _parse_args():
    parser = argparse.ArgumentParser()

    parser.add_argument(
        "-j", "--json-folder",
        required=True,
        help="The json folder in which to write the finney block json file."
    )

    return parser.parse_args()


def get_finney_block():
    # Testing multiprocessing module to see if it keeps the bittensor
    # function calls from lagging over time.
    try:
        with bittensor.Subtensor(network="finney") as subtensor:
            return subtensor.block
    except Exception as err:
        return f"{type(err).__name__}: {err}"


def write_finney_block_file(finney_block_data, json_folder):
    json_file = os.path.join(json_folder, FINNEY_BLOCK_FILE_NAME)

    # First remove existing file
    if os.path.isfile(json_file):
        bittensor.logging.info(f"Removing {json_file}")
        os.unlink(json_file)

    # Then write the new  file
    bittensor.logging.info(f"\nWriting data to file: {json_file}")
    with open(json_file, "w") as fd:
        json.dump(asdict(finney_block_data), fd, indent=4)


def main(options):
    bittensor.logging.enable_info()
    bittensor.logging.info("Getting finney block.")

    start_time = time.time()

    result = get_finney_block()
    finney_block_time = int(time.time())
    try:
        finney_block = int(result)
    except ValueError:
        finney_block = None
        bittensor.logging.error("Failed to get finney block.")
        bittensor.logging.error(result)

    finney_block_data = FinneyBlockData(
        block=finney_block,
        time=finney_block_time,
    )

    total_seconds = round(time.time() - start_time)
    total_time_formatted = format_time(total_seconds)
    bittensor.logging.info(f"Finney block gathering took {total_time_formatted}.\n")

    write_finney_block_file(finney_block_data, options.json_folder)


if __name__ == "__main__":
    try:
        options = _parse_args()

        # Bittensor import
        import bittensor

        main(options)
    except KeyboardInterrupt as exc:
        import traceback
        exc_list = traceback.format_exception_only(exc)
        exc_text = "\n" + "".join(exc_list).strip("\n")
        print(exc_text)
