#!/usr/bin/env python3

# standard imports
import argparse
import importlib
import json
import os
import subprocess
import sys
import time


def parse_args():
    parser = argparse.ArgumentParser()

    parser.add_argument(
        "-j", "--json-folder",
        help="The json folder in which to write the json files."
    )

    parser.add_argument(
        "-i", "--interval",
        type=float,
        default=0,
        help="The number of minutes between data gathering."
    )

    parser.add_argument(
        "-p", "--subprocess",
        action="store_true",
        help="When specified, run everything in a subprocess."
    )

    return parser.parse_args()


def format_time(total_time):
    m = total_time/60
    minutes = int(m)
    seconds = round((m - minutes)*60)

    runtime_text = [f"{minutes} minutes"] if minutes else []
    if seconds:
        runtime_text += [f"{seconds} seconds"]
    runtime_text = ", ".join(runtime_text)

    return runtime_text


def run(options):
    print("Gathering Burn Subnets")

    burn_subnets = set()
    process = subprocess.run(["pm2", "jlist"], stdout=subprocess.PIPE)
    pm2_output = json.loads(process.stdout)
    for pm2_process in pm2_output:
        if pm2_process["pm2_env"]["status"] != "online":
            continue

        script_path = pm2_process["pm2_env"]["pm_exec_path"]
        script_dir, script_name = os.path.split(script_path)
        script_module_name, script_ext = os.path.splitext(script_name)
        if script_ext != ".py":
            continue

        if script_dir not in sys.path:
            sys.path = [script_dir] + sys.path

        print(f"Checking {script_module_name}")
        try:
            script_module = importlib.import_module(script_module_name)
        except ModuleNotFoundError:
            continue

        try:
            burn_subnets.add(script_module.MAINNET_NETUID)
        except AttributeError:
            continue

    burn_subnets = sorted(burn_subnets)
    print("Burn Subnets:")
    print(burn_subnets)


def main(options):
    interval_seconds = round(options.interval * 60)
    if options.json_folder:
        os.makedirs(options.json_folder, exist_ok=True)

    while True:
        start_time = time.time()

        # Run the subnet data gathering.
        if options.subprocess:
            args = [options]
            with multiprocessing.Pool(processes=1) as pool:
                pool.apply(run, args)
        else:
            run(options)

        # Only gather the data once.
        if not interval_seconds:
            break

        total_seconds = round(time.time() - start_time)
        wait_seconds = interval_seconds - total_seconds
        if wait_seconds > 0:
            wait_time_formatted = format_time(wait_seconds)
            print(f"Waiting {wait_time_formatted}.")
            time.sleep(wait_seconds)
        else:
            print(
                f"Processing took {total_seconds} seconds which is longer "
                f"than {interval_seconds} seconds. Not waiting."
            )
    


if __name__ == "__main__":
    options = parse_args()

    if options.subprocess:
        import multiprocessing

    main(options)
