#!/usr/bin/env python3

# standard imports
import argparse
import os
import json
import subprocess
import tempfile


def parse_args():
    parser = argparse.ArgumentParser()

    parser.add_argument(
        "burn_venv",
        help="The path to the venv used for running burn code "
             "(without the bin/activate part)."
    )

    parser.add_argument(
        "--interval",
        type=int,
        default=2,
        help="The interval in blocks between restarts. Defaults to 2 blocks."
    )

    return parser.parse_args()


def main(options):
    burn_exec_dir = os.path.dirname(__file__)
    start_burn_script = os.path.join(
        os.path.expanduser(burn_exec_dir), "start_burn"
    )
    venv_path = options.burn_venv

    script_lines = ["#!/bin/bash", ""]

    data_file = os.path.expanduser(
        "~/.bittensor/burn_subnets_data/burn_subnets_data.json"
    )
    with open(data_file, "r") as fp:
        burn_subnets = json.load(fp)

    # even out the restarts across two epochs
    num_burn_subnets = len(burn_subnets)
    wait_seconds = options.interval * 12
    for i, burn_subnet in enumerate(burn_subnets):
        script_lines.append(f"echo Restarting subnet {burn_subnet}")
        burn_command = f"{start_burn_script} {venv_path} {burn_subnet}"
        script_lines.append(burn_command)
        if i < num_burn_subnets - 1:
            script_lines.extend(
                [f"echo Sleeping {wait_seconds} seconds", f"sleep {wait_seconds}", ""]
            )

    script_text = "\n".join(script_lines) + "\n"

    fp, restart_script = tempfile.mkstemp(
        prefix="restart_burn_subnets_", suffix=".sh"
    )
    os.close(fp)
    os.chmod(restart_script, 0o700)

    with open(restart_script, "w") as fp:
        fp.write(script_text)

    print("")
    print("Restarting all burn subnets")
    print(f"Shell script: {restart_script}")
    print("")
    try:
        subprocess.run([restart_script], check=True)
    except subprocess.CalledProcessError as exc:
        print(f"\nERROR: Command failed with error: {exc}")

    os.unlink(restart_script)


if __name__ == "__main__":
    options = parse_args()
    main(options)
