#!/usr/bin/env python3

# standard imports
import logging
import os
import sys

# Add local manual_weights_setter module to path
sys.path = [os.path.dirname(__file__)] + sys.path


# Debugging
DEBUG = True

# Script name
SCRIPT_NAME =  os.path.basename(__file__)


def main(options):
    # Import local manual_weights_setter module here
    # to suppress the bittensor --help info
    from manual_weights_setter.subnet_weights_checker import (
        SubnetWeightsChecker
    )

    if DEBUG:
        logger.setLevel(logging.DEBUG)
    else:
        logger.setLevel(logging.INFO)

    logger.info("")
    logger.info(f"Starting {SCRIPT_NAME}")
    logger.info("")

    SubnetWeightsChecker(SCRIPT_NAME, options)


if __name__ == "__main__":
    from manual_weights_setter.common import (
        logger,
        parse_ensure_set_weights_args
    )

    options = parse_ensure_set_weights_args()
    main(options)
