#!/usr/bin/env python3

# standard imports
import argparse
import os
import sys

# Add local manual_weights_setter module to path
sys.path = [os.path.dirname(__file__)] + sys.path


def parse_args():
    parser = argparse.ArgumentParser()

    parser.add_argument(
        "--add",
        type=int,
        nargs="+",
        default=[],
        help="The uids of the subnets to add to the ensure_set_weights pm2 process."
    )
    parser.add_argument(
        "--remove",
        type=int,
        nargs="+",
        default=[],
        help="The uids of the subnets to remove from the ensure_set_weights pm2 process."
    )

    return parser.parse_known_args()


def main(args, extra_args):
    # Import local manual_weights_setter module here
    # to suppress the bittensor --help info
    from manual_weights_setter.ensure_set_weights_starter import (
        EnsureSetWeightsStarter
    )

    EnsureSetWeightsStarter(args, extra_args)


if __name__ == "__main__":
    args, extra_args = parse_args()
    main(args, extra_args)
