#!/usr/bin/env python3

import argparse
import os
import requests


DEFAULT_PORT = 33393
USERNAME="rizzo"
PASSWORD="TaR3a5hJa6Kt0R5"


def parse_args():
    parser = argparse.ArgumentParser()

    parser.add_argument(
        "--host",
        required=True,
        help="The http host URL.")
    
    parser.add_argument(
        "--port",
        type=int,
        default=DEFAULT_PORT,
        help=f"The ssh port of the host URL. Default is {DEFAULT_PORT}")

    parser.add_argument(
        "--source",
        required=True,
        help="The source file relative to the host URL folder. "
             "Transferring an entire folder is not yet implemented.")

    parser.add_argument(
        "--dest",
        required=True,
        help="The destination folder.")

    return parser.parse_args()


def do_transfer(options):
    if os.path.isabs(options.source):
        print(f"ERROR: Source path {options.source} is not a relative path.")
        return

    if not os.path.isdir(options.dest):
        print(f"ERROR: Destination path {options.dest} does not exist as a directory.")
        return

    # Transfering a directory is not yet implemented.
    source_url = f"http://{options.host}:{options.port}/{options.source}"
    response = requests.get(source_url, auth=(USERNAME, PASSWORD))
    if response.status_code != 200:
        print(
            f"ERROR: Failed to obtain file to transfer."
            f"\nURL: {source_url}"
            f"\nStatus Code: {response.status_code}"
            f"\nReason: {response.reason}"
        )
        return

    dest_path = os.path.join(options.dest, options.source)
    # This is in case the --source file is a relative path containing subfolders.
    os.makedirs(os.path.dirname(dest_path))
    print(f"\nCopying remote file: {source_url}\nTo local file: {dest_path}")
    with open(dest_path, "w") as fp:
        fp.write(response.content.decode())


def main():
    options = parse_args()
    do_transfer(options)


if __name__ == "__main__":
    main()
